Fix update flow temperature service
BottlecapDave/HomeAssistant-OctopusEnergy pull request #1149
Opened 2024-12-31 21:43 UTC by lwis

A variety of fixes for this service, I had this working once but it must have broken after several refactors (I had it as seperate services but ultimately decided on just one). Sorry!

Serves me right for trying to refactor functional code while looking after a baby 🙈

2024-12-31 22:12 UTC, BottlecapDave requested changes
No problem. The feature hasn't gone live yet (I aiming for a release tomorrow), so no harm.

2024-12-31 22:12 UTC, BottlecapDave commented on custom_components/octopus_energy/api_client/__init__.py
> +      flowTemperature: {{
question: I assume it doesn't error when both are supplied regardless of if useWeatherCompensation is true or false? I only ask as the API looks like it expects `flowTemperature` to be null if `useWeatherCompensation` is false and `weatherCompensationValues` to be null if `useWeatherCompensation` is true.

2024-12-31 22:12 UTC, BottlecapDave commented on custom_components/octopus_energy/heat_pump/zone.py
> +        _LOGGER.warning(f'Suppress async_turn_on error due to mocking mode: {e}')
issue: `async_turn_on ` should be `async_set_heat_pump_flow_temp_config`

2025-01-01 10:55 UTC, lwis commented on custom_components/octopus_energy/api_client/__init__.py
> +      flowTemperature: {{
In my testing it seems to function the same when a full or partial configuration is provided.

2025-01-01 11:57 UTC, merged